[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 12

[window]
# startup_mode = "Fullscreen"
startup_mode = "Maximized"
padding = { x = 5, y = 1 }
opacity = 0.9

# 去除标题栏以及标题栏上的按钮(隐藏窗口按钮，最大化按钮，删除按钮)
decorations = "None" 
# option_as_alt = "OnlyLeft"


[scrolling]
history = 30000

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "N", mods = "Control|Alt", action = "SpawnNewInstance" },
{ key = "F11", action = "ToggleFullscreen" },
]

# CreateNewWindow 和 SpawnNewInstance 是有区别的
# 前者的窗口属于同一个进程，后者是不同的进程

[terminal]
# osc52 = "CopyPaste"
# for window
shell = { program = "wsl.exe", args = ["-d", "debain"]}
